# SonarQube project configuration
sonar.projectKey=Automation-POC
sonar.projectName=Automation-framework
sonar.sources=src/main/java,src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.sourceEncoding=UTF-8
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=target/surefire-reports 
sonar.host.url=http://localhost:9000
sonar.exclusions=src/test/java/com/automation/base/BaseTest.java